dev_env/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from dev_env.settings import GRAPHENE_SUPPORT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_ledger.urls', namespace='django_ledger')),
]

try:
    if GRAPHENE_SUPPORT:
        # checking for graphene_django installation to provide and enable graphql services...
        from graphene_django.views import GraphQLView
        from django_ledger.contrib.django_ledger_graphene.api import schema

        urlpatterns += [
            path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema)))
        ]
except ImportError:
    pass

django-ledger/models/accounts.py
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.db.models.signals import pre_save, post_init


class AccountModel(models.Model):
    ACCOUNT_ROLE = [
        ('Assets', (
            ('ca', 'Current Asset'),
            ('lti', 'Long Term Investments'),
            ('ppe', 'Property Plant & Equipment'),
            ('ia', 'Intangible Assets'),
            ('aadj', 'Asset Adjustments'),
        )
         ),

        ('Liabilities', (
            ('cl', 'Current Liabilities'),
            ('ltl', 'Long Term Liabilities'),
        )
         ),

        ("Equity", (
            ('cap', 'Capital'),
            ('cadj', 'Capital Adjustments'),
            ('in', 'Income'),
            ('ex', 'Expense'),
            ('capex', 'Capital Expenditure')
        )
         ),

        ("Other", (
            ('excl', 'Excluded'),
        )
         )
    ]

    BALANCE_TYPE = [
        ('credit', 'Credit'),
        ('debit', 'Debit')
    ]

    code = models.CharField(max_length=5, unique=True)
    parent = models.CharField(max_length=5, null=True, blank=True)
    name = models.TextField()
    role = models.CharField(max_length=10, choices=ACCOUNT_ROLE)
    role_bs = models.CharField(max_length=20, null=True)
    balance_type = models.CharField(max_length=6, choices=BALANCE_TYPE)

    locked = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return '{x1} - {x5}: {x2} ({x3}/{x4})'.format(x1=self.role_bs.upper(),
                                                      x2=self.name,
                                                      x3=self.role.upper(),
                                                      x4=self.balance_type,
                                                      x5=self.code)

    def get_bs_role(self):
        if self.role:
            for role, value in dict(self.ACCOUNT_ROLE).items():
                if self.role in [x[0] for x in value]:
                    return role.lower()

    def set_bs_role(self):
        """
        Account Balance Sheet Role is automatically checked during save and Model's clean() operation.

        """
        if not self.role_bs:
            self.role_bs = self.get_bs_role()

    def check_bs_role(self):
        return self.role_bs == self.get_bs_role()

    def clean(self):

        if not self.check_bs_role():
            self.set_bs_role()

    def get_balance(self):

        credits = self.txs.filter(
            tx_type__exact='credit').aggregate(
            credits=Coalesce(Sum('amount'), 0))['credits']

        debits = self.txs.filter(
            tx_type__exact='debit').aggregate(
            debits=Coalesce(Sum('amount'), 0))['debits']

        if self.balance_type == 'credit':
            return credits - debits
        elif self.balance_type == 'debit':
            return debits - credits


# AccountModel Signals ----------------
def accountmodel_postinit(sender, instance, *args, **kwargs):
    print('Hello Account {x1}-{x2} Post Init'.format(x1=instance.code,
                                                     x2=instance.name))


post_init.connect(accountmodel_postinit, sender=AccountModel)


def accountmodel_presave(sender, instance, raw, using, update_fields, *args, **kwargs):
    print('Hello Account {x1}-{x2} Pre Save'.format(x1=instance.code,
                                                    x2=instance.name))
    if not instance.check_bs_role():
        instance.set_bs_role()


pre_save.connect(accountmodel_presave, sender=AccountModel)

django-ledger/models/journalentry.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.db.models.signals import pre_save


class JournalEntryModel(models.Model):

    FREQUENCY = (
        ('nr', 'Non-Recurring'),
        ('d', 'Daily'),
        ('m', 'Monthly'),
        ('q', 'Quarterly'),
        ('y', 'Yearly'),
        ('sm', 'Monthly Series'),
        ('sy', 'Yearly Series'),
    )

    ACTIVITY = (
        ('op', 'Operating'),
        ('fin', 'Financing'),
        ('inv', 'Investing'),
        ('other', 'Other'),
    )

    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    desc = models.CharField(max_length=70, blank=True, null=True)
    freq = models.CharField(max_length=2,
                            choices=FREQUENCY)
    activity = models.CharField(choices=ACTIVITY,
                                max_length=5)
    origin = models.CharField(max_length=30, blank=True, null=True)

    parent = models.ForeignKey('self',
                               blank=True,
                               null=True,
                               related_name="children",
                               on_delete=models.CASCADE)

    ledger = models.ForeignKey('books.LedgerModel',
                               related_name='jes',
                               on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return 'JE ID: {x1} - Desc: {x2}'.format(x1=self.pk, x2=self.desc)

    def get_balances(self):
        credits = self.txs.filter(tx_type__iexact='credit').aggregate(Sum('amount'))
        debits = self.txs.filter(tx_type__iexact='debit').aggregate(Sum('amount'))
        balances = dict()
        balances['credits'] = credits
        balances['debits'] = debits

        if credits == debits:
            balances['valid'] = True
        else:
            balances['valid'] = False
        return balances

    def je_is_valid(self):
        return self.get_balances()['valid']

    def clean(self):

        # check1 = 'JE must have either a "ledger" or "forecast" models assigned'
        # if self.ledger is None and self.actuals is None:
        #     raise ValidationError(check1)
        # elif self.forecast is not None and self.actuals is not None:
        #     raise ValidationError(check1)

        check2 = 'Debits and credits do not balance'
        if not self.je_is_valid():
            raise ValidationError(check2)

        check3 = 'Recurring JE must have an "end_date"'
        if self.freq != 'nr':
            if self.end_date is None:
                raise ValidationError(check3)
            else:
                self.end_date = self.start_date

                # todo: 'JE Series validator'
                # check4 = 'Series validator'


def je_presave(sender, instance, *args, **kwargs):
    instance.clean_fields()


pre_save.connect(je_presave, sender=JournalEntryModel)

django_ledger/models/bill.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
Pranav P Tulshyan <ptulshyan77@gmail.com>

"""
from datetime import date
from decimal import Decimal
from string import ascii_uppercase, digits
from typing import Union
from uuid import uuid4

from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Q, Sum, Count, Case, When, Value, ExpressionWrapper, IntegerField, F
from django.db.models.signals import post_delete
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.timezone import localdate
from django.utils.translation import gettext_lazy as _

from django_ledger.models import EntityModel
from django_ledger.models import LazyLoader
from django_ledger.models.mixins import CreateUpdateMixIn, LedgerWrapperMixIn, MarkdownNotesMixIn, PaymentTermsMixIn
from django_ledger.settings import DJANGO_LEDGER_DOCUMENT_NUMBER_PADDING, DJANGO_LEDGER_BILL_NUMBER_PREFIX

lazy_loader = LazyLoader()

BILL_NUMBER_CHARS = ascii_uppercase + digits

"""
Bill : it refers the purchase Invoice/ Tax Invoice/ Purchase Bill which is issued by the Suppliers/ Vendors for the supply of goods or services
The model manages all the Purchase Invoice/ Bills for the purhases mde by the entity.
In addition to tracking the bill amount , it tracks the paid and due amount


"""


# def generate_bill_number(length: int = 10, prefix: bool = True) -> str:
#     """
#     A function that generates a random bill identifier for new bill models.
#     Params:
#
#     @prefix:whether the prefix is to be added or not.
#     @length: The length of the bill number.
#     :return: A string representing a random bill identifier.
#
#     """
#     bill_number = ''.join(choices(BILL_NUMBER_CHARS, k=length))
#     if prefix:
#         bill_number = 'B-' + bill_number
#     return bill_number


class BillModelQuerySet(models.QuerySet):
    """
    A custom defined Query Set for the BillMOdel.
    This implements multiple methods or queries that we need to run to get a status of bills.
    For e.g : We might want to have list of bills which are paid, unpaid, Due , OverDue, Approved, In draft stage.
    All these separate functions will assist in making such queries and building customized reports.
    """

    def paid(self):
        return self.filter(bill_status__exact=BillModel.BILL_STATUS_PAID)

    def approved(self):
        return self.filter(bill_status__exact=BillModel.BILL_STATUS_APPROVED)

    def active(self):
        return self.filter(
            Q(bill_status__exact=BillModel.BILL_STATUS_APPROVED) |
            Q(bill_status__exact=BillModel.BILL_STATUS_PAID)
        )


class BillModelManager(models.Manager):
    """
    A custom defined Bill Model Manager that will act as an inteface to handling the DB queries to the Bill Model.
    The default "get_queryset" has been overridden to refer the customdefined "BillModelQuerySet"

    """

    def get_queryset(self):
        return BillModelQuerySet(self.model, using=self._db)

    def for_user(self, user_model):
        return self.get_queryset().filter(
            Q(ledger__entity__admin=user_model) |
            Q(ledger__entity__managers__in=[user_model])
        )

    def for_entity(self, entity_slug, user_model):
        if isinstance(entity_slug, EntityModel):
            return self.get_queryset().filter(
                Q(ledger__entity=entity_slug) & (
                        Q(ledger__entity__admin=user_model) |
                        Q(ledger__entity__managers__in=[user_model])
                )
            )
        elif isinstance(entity_slug, str):
            return self.get_queryset().filter(
                Q(ledger__entity__slug__exact=entity_slug) & (
                        Q(ledger__entity__admin=user_model) |
                        Q(ledger__entity__managers__in=[user_model])
                )
            )

    def for_entity_unpaid(self, entity_slug, user_model):
        qs = self.for_entity(entity_slug=entity_slug,
                             user_model=user_model)
        return qs.approved()


class BillModelAbstract(LedgerWrapperMixIn,
                        PaymentTermsMixIn,
                        MarkdownNotesMixIn,
                        CreateUpdateMixIn):
    """
    This is the main abstract class which the Bill Model database will inherit, and it contains the fields/columns/attributes which the said table will have.
    In addition to the attributes mentioned below, it also has the the fields/columns/attributes mentioned in below MixIn:
    
    LedgerWrapperMixIn
    PaymentTermsMixIn
    MarkdownNotesMixIn
    CreateUpdateMixIn
    
    Read about these mixin here.

    Below are the fields specific to the bill model.
    @uuid : this is a unique primary key generated for the table. the default value of this fields is set as the unique uuid generated.
    @bill_number: This is a slug  Field and hence a random bill number with Max Length of 20 will be defined
    @bill_status: Any bill can have the status as either of the choices as mentioned under "BILL_STATUS" By default , the status will be "Draft"
    @xref: This is the fiedl for capturing of any External reference number like the PO number of the buyer.Any othere reference number like the Vendor code in buyer books may also be captured.
    @vendor: This is the foreign key refernce to the Vendor code from whom the purchase has been made.
    @additional_info: Any additional info about the Bill
    @bill_items: This refers to the material code present in the items model. So, we have a drop down to choose which item has been procured in a bill

    Other fields to capture the dates at which the review and approval was

    

    """
    REL_NAME_PREFIX = 'bill'
    IS_DEBIT_BALANCE = False
    ALLOW_MIGRATE = True

    BILL_STATUS_DRAFT = 'draft'
    BILL_STATUS_REVIEW = 'in_review'
    BILL_STATUS_APPROVED = 'approved'
    BILL_STATUS_PAID = 'paid'
    BILL_STATUS_VOID = 'void'
    BILL_STATUS_CANCELED = 'canceled'

    BILL_STATUS = [
        (BILL_STATUS_DRAFT, _('Draft')),
        (BILL_STATUS_REVIEW, _('In Review')),
        (BILL_STATUS_APPROVED, _('Approved')),
        (BILL_STATUS_PAID, _('Paid')),
        (BILL_STATUS_CANCELED, _('Canceled')),
        (BILL_STATUS_VOID, _('Void'))
    ]

    # todo: implement Void Bill (& Invoice)....
    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    bill_number = models.SlugField(max_length=20, verbose_name=_('Bill Number'), editable=False)
    bill_status = models.CharField(max_length=10,
                                   choices=BILL_STATUS,
                                   default=BILL_STATUS[0][0],
                                   verbose_name=_('Bill Status'))
    xref = models.SlugField(null=True, blank=True, verbose_name=_('External Reference Number'))
    vendor = models.ForeignKey('django_ledger.VendorModel',
                               on_delete=models.CASCADE,
                               verbose_name=_('Vendor'))
    additional_info = models.JSONField(blank=True,
                                       null=True,
                                       verbose_name=_('Bill Additional Info'))
    bill_items = models.ManyToManyField('django_ledger.ItemModel',
                                        through='django_ledger.ItemTransactionModel',
                                        through_fields=('bill_model', 'item_model'),
                                        verbose_name=_('Bill Items'))

    ce_model = models.ForeignKey('django_ledger.EstimateModel',
                                 on_delete=models.RESTRICT,
                                 null=True,
                                 blank=True,
                                 verbose_name=_('Associated Customer Job/Estimate'))

    date_draft = models.DateField(null=True, blank=True, verbose_name=_('Draft Date'))
    date_in_review = models.DateField(null=True, blank=True, verbose_name=_('In Review Date'))
    date_approved = models.DateField(null=True, blank=True, verbose_name=_('Approved Date'))
    date_paid = models.DateField(null=True, blank=True, verbose_name=_('Paid Date'))
    date_void = models.DateField(null=True, blank=True, verbose_name=_('Void Date'))
    date_canceled = models.DateField(null=True, blank=True, verbose_name=_('Canceled Date'))

    objects = BillModelManager()

    class Meta:
        abstract = True
        ordering = ['-updated']
        verbose_name = _('Bill')
        verbose_name_plural = _('Bills')
        indexes = [
            models.Index(fields=['bill_status']),
            models.Index(fields=['terms']),

            models.Index(fields=['cash_account']),
            models.Index(fields=['prepaid_account']),
            models.Index(fields=['unearned_account']),

            models.Index(fields=['date_due']),
            models.Index(fields=['date_draft']),
            models.Index(fields=['date_in_review']),
            models.Index(fields=['date_approved']),
            models.Index(fields=['date_paid']),
            models.Index(fields=['date_canceled']),
            models.Index(fields=['date_void']),

            models.Index(fields=['vendor']),
        ]

    def __str__(self):
        return f'Bill: {self.bill_number}'

    # Configuration...
    def configure(self,
                  entity_slug: Union[str, EntityModel],
                  user_model,
                  ledger_posted: bool = False,
                  bill_desc: str = None,
                  commit: bool = False):

        if isinstance(entity_slug, str):
            entity_qs = EntityModel.objects.for_user(
                user_model=user_model)
            entity_model: EntityModel = get_object_or_404(entity_qs, slug__exact=entity_slug)

django_ledger/templates/django_ledger/tags/bill_table.html
{% load django_ledger %}
{% load i18n %}

<div class="table-container">

    <table class="table is-fullwidth is-narrow is-striped is-bordered django-ledger-table-bottom-margin-75">
        <thead>
        <tr>
            <th>Bill Number</th>
            <th>Status</th>
            <th>Bill Date</th>
            <th>Vendor</th>
            <th>Amount Due</th>
            <th>Payments</th>
            <th>Past Due?</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for bill in bills %}
            <tr id="{{ bill.get_html_id }}">
                <td>{{ bill.bill_number }}</td>
                <td>{{ bill.get_bill_status_display }}</td>
                <td>{{ bill.date }}</td>
                <td>{{ bill.vendor.vendor_name }}</td>
                <td id="{{ bill.get_html_amount_due_id }}">{% currency_symbol %}{{ bill.amount_due | currency_format }}</td>
                <td id="{{ bill.get_html_amount_paid_id }}">{% currency_symbol %}{{ bill.amount_paid | currency_format }}</td>
                <td class="has-text-centered">
                    {% if bill.is_past_due %}
                        <span class="icon is-small has-text-danger">{% icon 'bi:check-circle-fill' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-success">{% icon 'clarity:no-access-solid' 24 %}</span>
                    {% endif %}
                </td>
                <td class="has-text-centered">
                    <div class="dropdown is-right is-hoverable" id="bill-action-{{ bill.uuid }}">
                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined is-dark"
                                    aria-haspopup="true"
                                    aria-controls="dropdown-menu">
                                <span>Actions</span>
                                <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu-{{ bill.uuid }}" role="menu">
                            <div class="dropdown-content">
                                <a href="{% url 'django_ledger:bill-detail' entity_slug=entity_slug bill_pk=bill.uuid %}"
                                   class="dropdown-item has-text-success">Details</a>
                                <a href="{% url 'django_ledger:bill-update' entity_slug=entity_slug bill_pk=bill.uuid %}"
                                   class="dropdown-item has-text-warning-dark">Update</a>
{#                                {% if not bill.paid %}#}
{#                                    {% modal_action bill 'get' entity_slug %}#}
{#                                    <a onclick="djLedger.showModal('{{ bill.get_html_id }}')"#}
{#                                       class="dropdown-item has-text-weight-bold has-text-info">{% trans 'Mark as Paid' %}</a>#}
{#                                {% endif %}#}
{#                                <a href="{% url 'django_ledger:bill-delete' entity_slug=entity_slug bill_pk=bill.uuid %}"#}
{#                                   class="dropdown-item has-text-weight-bold has-text-danger">{% trans ' Delete' %}</a>#}
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

django_ledger/templates/django_ledger/tags/customer_estimate_table.html
{% load django_ledger %}
{% load i18n %}

<div class="table-container">

    <table class="table is-fullwidth is-narrow is-striped is-bordered django-ledger-table-bottom-margin-75">
        <thead>
        <tr>
            <th>{% trans 'Customer' %}</th>
            <th>{% trans 'Title' %}</th>
            <th>{% trans 'Sales Price' %}</th>
            <th>{% trans 'GM%' %}</th>
            <th>{% trans 'Approved' %}</th>
            <th>{% trans 'Completed' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for cj in ce_list %}
            <tr id="{{ cj.get_html_id }}">
                <td>{{ cj.customer.customer_name }}</td>
                <td>{{ cj.title }}</td>
                <td class="has-text-centered">{% currency_symbol %}{{ cj.revenue_estimate | currency_format }}</td>
                <td class="has-text-centered">{% currency_symbol %}{{ cj.gross_margin_estimate | percentage }}</td>
                <td class="has-text-centered">
                    {% if cj.is_approved %}
                        <span class="icon is-small has-text-success">{% icon 'bi:check-circle-fill' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'clarity:no-access-solid' 24 %}</span>
                    {% endif %}
                </td>
                <td class="has-text-centered">
                    {% if cj.is_completed %}
                        <span class="icon is-small has-text-success">{% icon 'bi:check-circle-fill' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'clarity:no-access-solid' 24 %}</span>
                    {% endif %}
                </td>

                {# ACTIONS #}
                <td class="has-text-centered">
                    <div class="dropdown is-right is-hoverable" id="cj-action-{{ cj.uuid }}">
                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined is-dark"
                                    aria-haspopup="true"
                                    aria-controls="dropdown-menu">
                                <span>{% trans 'Actions' %}</span>
                                <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu-{{ cj.uuid }}" role="menu">
                            <div class="dropdown-content">
                                <a href="{% url 'django_ledger:customer-estimate-detail' entity_slug=entity_slug ce_pk=cj.uuid %}"
                                   class="dropdown-item has-text-success">Details</a>
                                {#                                <a href="{% url 'django_ledger:cj-update' entity_slug=entity_slug cj_pk=cj.uuid %}"#}
                                {#                                   class="dropdown-item has-text-warning-dark">Update</a>#}
                                {#                                {% if not cj.paid %}#}
                                {#                                    {% modal_action cj 'get' entity_slug %}#}
                                {#                                    <a onclick="djLedger.showModal('{{ cj.get_html_id }}')"#}
                                {#                                       class="dropdown-item has-text-weight-bold has-text-info">{% trans 'Mark as Paid' %}</a>#}
                                {#                                {% endif %}#}
                                {#                                <a href="{% url 'django_ledger:cj-delete' entity_slug=entity_slug cj_pk=cj.uuid %}"#}
                                {#                                   class="dropdown-item has-text-weight-bold has-text-danger">{% trans ' Delete' %}</a>#}
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

django_ledger/templates/django_ledger/tags/customer_job_item_formset.html
{% load trans from i18n %}
{% load django_ledger %}

<form action="{% url 'django_ledger:customer-estimate-update-items' entity_slug=entity_slug customer_job_pk=customer_job_pk %}"
      method="post">
    <div class="columns is-multiline">
        <div class="column is-12">
            <h1 class="is-size-1">{% trans 'Customer Job Items' %}</h1>
        </div>
        <div class="column is-12">
            <div class="table-container">
                {% csrf_token %}
                {{ item_formset.non_form_errors }}
                {{ item_formset.management_form }}
                <table class="table is-fullwidth is-narrow is-striped is-bordered">
                    <thead>
                    <tr>
                        <th>{% trans 'Item' %}</th>
                        <th>{% trans 'Quantity' %}</th>
                        <th>{% trans 'Unit Cost' %}</th>
                        <th>{% trans 'Unit Sales Price' %}</th>
                        <th>{% trans 'Business Unit' %}</th>
                        <th>{% trans 'Total Cost' %}</th>
                        <th>{% trans 'Total Revenue' %}</th>
                        <th>{% trans 'Delete' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for f in item_formset %}
                        <tr>
                            <td>
                                {% for hidden_field in f.hidden_fields %}
                                    {{ hidden_field }}
                                {% endfor %}
                                {{ f.item_model }}
                                {% if f.errors %}
                                    <span class="has-text-danger">{{ f.errors }}</span>
                                {% endif %}
                            </td>
                            <td id="{{ f.instance.html_id_quantity }}">{{ f.quantity }}</td>
                            <td id="{{ f.instance.html_id_unit_cost }}">{{ f.unit_cost }}</td>
                            <td>{{ f.ce_unit_revenue_estimate }}</td>
                            <td>{{ f.entity_unit }}</td>
                            <td class="has-text-right" id="{{ f.instance.html_id_total_amount }}">
                                {% currency_symbol %}{{ f.instance.total_amount | currency_format }}</td>
                            <td class="has-text-right" id="{{ f.instance.html_id_total_amount }}">
                                {% currency_symbol %}{{ f.instance.ce_revenue_estimate | currency_format }}</td>
                            <td class="has-text-centered">
                                {% if item_formset.can_delete %}
                                    {{ f.DELETE }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th class="has-text-right">{% trans 'Total' %}</th>
                        <th class="has-text-right">{% currency_symbol %}{{ cost_estimate | currency_format }}</th>
                        <th class="has-text-right">{% currency_symbol %}{{ revenue_estimate | currency_format }}</th>
                        <th></th>
                    </tr>
                    </tfoot>

                </table>
            </div>
        </div>
        <div class="column is-12">
            {% if not item_formset.has_po %}
                <a href="{% url 'django_ledger:product-create' entity_slug=entity_slug %}"
                   class="button is-primary">{% trans 'New Item' %}</a>
            {% endif %}
            <button class="button is-primary">{% trans 'Save' %}</button>
        </div>
    </div>
</form>

django_ledger/templates/django_ledger/tags/data_import_job_table.html
{% load django_ledger %}

<div class="table-container">
    <table class="table is-fullwidth">
        <thead>
        <tr>
            <th>Status</th>
            <th>Description</th>
            <th>Ledger</th>
            <th>Created</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for job in import_jobs %}
            <tr>
                <td>{{ job.status }}</td>
                <td>{{ job.description }}</td>
                <td>{{ job.ledger }}</td>
                <td>{{ job.created }}</td>
                <td>
                    <a class="button is-small is-info is-outlined"
                       href="{% url 'django_ledger:data-import-job-txs' entity_slug=view.kwargs.entity_slug job_pk=job.uuid %}">Txs</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

</div>

django_ledger/templates/django_ledger/tags/default_entity_form.html
<form id="djetler-set-entity-form"
      action="{% url 'django_ledger:entity-set-default' %}"
      method="post">
    {% csrf_token %}
    <div class="field">
        <div class="control">
            <div class="select is-inf is-small">
                {{ default_entity_form.entity_model }}
            </div>
        </div>
    </div>
</form>

django_ledger/templates/django_ledger/tags/transactions.html
{% load django_ledger %}

<table class="table is-fullwidth">
    <tr>
        <th>Account</th>
        <th>Account Name</th>
        <th>Credit</th>
        <th>Debit</th>
        <th>Description</th>
    </tr>
    {% for tx in txs %}
        <tr>
            <td>{{ tx.account.code }}</td>
            <td>{{ tx.account.name }}</td>
            <td>{% if tx.tx_type == 'credit' %}${{ tx.amount | cs_thousands }}{% endif %}</td>
            <td>{% if tx.tx_type == 'debit' %}${{ tx.amount | cs_thousands }}{% endif %}</td>
            <td>{{ tx.description }}</td>
        </tr>
    {% endfor %}
    <tr class="has-text-weight-bold">
        <td>Total</td>
        <td></td>
        <td>${{ total_credits | cs_thousands }}</td>
        <td>${{ total_debits | cs_thousands }}</td>
    </tr>
</table>